<?php

namespace Database\Seeders;

use App\Models\Letter;
use Illuminate\Database\Seeder;

/**
 * Data bersumber dari: https://github.com/dyazincahya/iqro-json
 * CDN: https://cdn.jsdelivr.net/gh/dyazincahya/iqro-json/hijaiyah-letters-with-vowels.json
 */
class LetterSeeder extends Seeder
{
    public function run(): void
    {
        $letters = [
            [
                'char_arabic' => 'ا',
                'name' => 'Alif',
                'read_latin' => 'A',
                'order_sequence' => 1,
                'pronunciation_desc' => 'Mulut terbuka lebar. Suara keluar tanpa hambatan.',
                'fathah'  => ['latin' => 'A',   'arabic' => 'اَ'],
                'kasrah'  => ['latin' => 'I',   'arabic' => 'اِ'],
                'dhammah' => ['latin' => 'U',   'arabic' => 'اُ'],
            ],
            [
                'char_arabic' => 'ب',
                'name' => 'Ba',
                'read_latin' => 'Ba',
                'order_sequence' => 2,
                'pronunciation_desc' => 'Bibir tertutup lalu dibuka. Seperti huruf B dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Ba',  'arabic' => 'بَ'],
                'kasrah'  => ['latin' => 'Bi',  'arabic' => 'بِ'],
                'dhammah' => ['latin' => 'Bu',  'arabic' => 'بُ'],
            ],
            [
                'char_arabic' => 'ت',
                'name' => 'Ta',
                'read_latin' => 'Ta',
                'order_sequence' => 3,
                'pronunciation_desc' => 'Ujung lidah menyentuh pangkal gigi seri atas.',
                'fathah'  => ['latin' => 'Ta',  'arabic' => 'تَ'],
                'kasrah'  => ['latin' => 'Ti',  'arabic' => 'تِ'],
                'dhammah' => ['latin' => 'Tu',  'arabic' => 'تُ'],
            ],
            [
                'char_arabic' => 'ث',
                'name' => 'Tsa',
                'read_latin' => 'Tsa',
                'order_sequence' => 4,
                'pronunciation_desc' => 'Ujung lidah dikeluarkan sedikit di antara gigi atas dan bawah.',
                'fathah'  => ['latin' => 'Tsa', 'arabic' => 'ثَ'],
                'kasrah'  => ['latin' => 'Tsi', 'arabic' => 'ثِ'],
                'dhammah' => ['latin' => 'Tsu', 'arabic' => 'ثُ'],
            ],
            [
                'char_arabic' => 'ج',
                'name' => 'Jim',
                'read_latin' => 'Ja',
                'order_sequence' => 5,
                'pronunciation_desc' => 'Tengah lidah menyentuh langit-langit mulut. Seperti J dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Ja',  'arabic' => 'جَ'],
                'kasrah'  => ['latin' => 'Ji',  'arabic' => 'جِ'],
                'dhammah' => ['latin' => 'Ju',  'arabic' => 'جُ'],
            ],
            [
                'char_arabic' => 'ح',
                'name' => 'Ha',
                'read_latin' => 'Ha',
                'order_sequence' => 6,
                'pronunciation_desc' => 'Keluar dari tengah tenggorokan dengan bersih dan terang.',
                'fathah'  => ['latin' => 'Ha',  'arabic' => 'حَ'],
                'kasrah'  => ['latin' => 'Hi',  'arabic' => 'حِ'],
                'dhammah' => ['latin' => 'Hu',  'arabic' => 'حُ'],
            ],
            [
                'char_arabic' => 'خ',
                'name' => 'Kha',
                'read_latin' => 'Kha',
                'order_sequence' => 7,
                'pronunciation_desc' => 'Keluar dari ujung tenggorokan seperti suara mendengkur halus.',
                'fathah'  => ['latin' => 'Kha', 'arabic' => 'خَ'],
                'kasrah'  => ['latin' => 'Khi', 'arabic' => 'خِ'],
                'dhammah' => ['latin' => 'Khu', 'arabic' => 'خُ'],
            ],
            [
                'char_arabic' => 'د',
                'name' => 'Dal',
                'read_latin' => 'Da',
                'order_sequence' => 8,
                'pronunciation_desc' => 'Ujung lidah menyentuh pangkal gigi seri atas, bunyi tebal.',
                'fathah'  => ['latin' => 'Da',  'arabic' => 'دَ'],
                'kasrah'  => ['latin' => 'Di',  'arabic' => 'دِ'],
                'dhammah' => ['latin' => 'Du',  'arabic' => 'دُ'],
            ],
            [
                'char_arabic' => 'ذ',
                'name' => 'Dzal',
                'read_latin' => 'Dza',
                'order_sequence' => 9,
                'pronunciation_desc' => 'Ujung lidah dikeluarkan sedikit di antara gigi, seperti Dzal.',
                'fathah'  => ['latin' => 'Dza', 'arabic' => 'ذَ'],
                'kasrah'  => ['latin' => 'Dzi', 'arabic' => 'ذِ'],
                'dhammah' => ['latin' => 'Dzu', 'arabic' => 'ذُ'],
            ],
            [
                'char_arabic' => 'ر',
                'name' => 'Ra',
                'read_latin' => 'Ra',
                'order_sequence' => 10,
                'pronunciation_desc' => 'Ujung lidah bergetar menyentuh gusi atas. Seperti R bergetar.',
                'fathah'  => ['latin' => 'Ra',  'arabic' => 'رَ'],
                'kasrah'  => ['latin' => 'Ri',  'arabic' => 'رِ'],
                'dhammah' => ['latin' => 'Ru',  'arabic' => 'رُ'],
            ],
            [
                'char_arabic' => 'ز',
                'name' => 'Za',
                'read_latin' => 'Za',
                'order_sequence' => 11,
                'pronunciation_desc' => 'Ujung lidah di belakang gigi seri bawah, mendengung.',
                'fathah'  => ['latin' => 'Za',  'arabic' => 'زَ'],
                'kasrah'  => ['latin' => 'Zi',  'arabic' => 'زِ'],
                'dhammah' => ['latin' => 'Zu',  'arabic' => 'زُ'],
            ],
            [
                'char_arabic' => 'س',
                'name' => 'Sin',
                'read_latin' => 'Sa',
                'order_sequence' => 12,
                'pronunciation_desc' => 'Mendesis dari celah gigi depan. Seperti S dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Sa',  'arabic' => 'سَ'],
                'kasrah'  => ['latin' => 'Si',  'arabic' => 'سِ'],
                'dhammah' => ['latin' => 'Su',  'arabic' => 'سُ'],
            ],
            [
                'char_arabic' => 'ش',
                'name' => 'Syin',
                'read_latin' => 'Sya',
                'order_sequence' => 13,
                'pronunciation_desc' => 'Udara menyebar di dalam mulut. Seperti Sy dalam Syarat.',
                'fathah'  => ['latin' => 'Sya', 'arabic' => 'شَ'],
                'kasrah'  => ['latin' => 'Syi', 'arabic' => 'شِ'],
                'dhammah' => ['latin' => 'Syu', 'arabic' => 'شُ'],
            ],
            [
                'char_arabic' => 'ص',
                'name' => 'Shad',
                'read_latin' => 'Sha',
                'order_sequence' => 14,
                'pronunciation_desc' => 'Mendesis tebal, pangkal lidah naik ke langit-langit.',
                'fathah'  => ['latin' => 'Sha', 'arabic' => 'صَ'],
                'kasrah'  => ['latin' => 'Shi', 'arabic' => 'صِ'],
                'dhammah' => ['latin' => 'Shu', 'arabic' => 'صُ'],
            ],
            [
                'char_arabic' => 'ض',
                'name' => 'Dhad',
                'read_latin' => 'Dha',
                'order_sequence' => 15,
                'pronunciation_desc' => 'Sisi lidah menyentuh geraham atas, bunyi tebal dan berat.',
                'fathah'  => ['latin' => 'Dha', 'arabic' => 'ضَ'],
                'kasrah'  => ['latin' => 'Dhi', 'arabic' => 'ضِ'],
                'dhammah' => ['latin' => 'Dhu', 'arabic' => 'ضُ'],
            ],
            [
                'char_arabic' => 'ط',
                'name' => 'Tha',
                'read_latin' => 'Tha',
                'order_sequence' => 16,
                'pronunciation_desc' => 'Tebal, ujung lidah di pangkal gigi seri atas, penuh tekanan.',
                'fathah'  => ['latin' => 'Tha', 'arabic' => 'طَ'],
                'kasrah'  => ['latin' => 'Thi', 'arabic' => 'طِ'],
                'dhammah' => ['latin' => 'Thu', 'arabic' => 'طُ'],
            ],
            [
                'char_arabic' => 'ظ',
                'name' => 'Zha',
                'read_latin' => 'Zha',
                'order_sequence' => 17,
                'pronunciation_desc' => 'Tebal, ujung lidah dikeluarkan sedikit di antara gigi.',
                'fathah'  => ['latin' => 'Zha', 'arabic' => 'ظَ'],
                'kasrah'  => ['latin' => 'Zhi', 'arabic' => 'ظِ'],
                'dhammah' => ['latin' => 'Zhu', 'arabic' => 'ظُ'],
            ],
            [
                'char_arabic' => 'ع',
                'name' => 'Ain',
                'read_latin' => "'A",
                'order_sequence' => 18,
                'pronunciation_desc' => 'Keluar dari tengah tenggorokan dengan ditekan kuat.',
                'fathah'  => ['latin' => "'A",  'arabic' => 'عَ'],
                'kasrah'  => ['latin' => "'I",  'arabic' => 'عِ'],
                'dhammah' => ['latin' => "'U",  'arabic' => 'عُ'],
            ],
            [
                'char_arabic' => 'غ',
                'name' => 'Ghain',
                'read_latin' => 'Gha',
                'order_sequence' => 19,
                'pronunciation_desc' => 'Keluar dari ujung tenggorokan, seperti berkumur.',
                'fathah'  => ['latin' => 'Gha', 'arabic' => 'غَ'],
                'kasrah'  => ['latin' => 'Ghi', 'arabic' => 'غِ'],
                'dhammah' => ['latin' => 'Ghu', 'arabic' => 'غُ'],
            ],
            [
                'char_arabic' => 'ف',
                'name' => 'Fa',
                'read_latin' => 'Fa',
                'order_sequence' => 20,
                'pronunciation_desc' => 'Gigi seri atas menyentuh bibir bawah. Seperti F dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Fa',  'arabic' => 'فَ'],
                'kasrah'  => ['latin' => 'Fi',  'arabic' => 'فِ'],
                'dhammah' => ['latin' => 'Fu',  'arabic' => 'فُ'],
            ],
            [
                'char_arabic' => 'ق',
                'name' => 'Qaf',
                'read_latin' => 'Qa',
                'order_sequence' => 21,
                'pronunciation_desc' => 'Pangkal lidah bagian belakang menyentuh langit-langit lunak.',
                'fathah'  => ['latin' => 'Qa',  'arabic' => 'قَ'],
                'kasrah'  => ['latin' => 'Qi',  'arabic' => 'قِ'],
                'dhammah' => ['latin' => 'Qu',  'arabic' => 'قُ'],
            ],
            [
                'char_arabic' => 'ك',
                'name' => 'Kaf',
                'read_latin' => 'Ka',
                'order_sequence' => 22,
                'pronunciation_desc' => 'Pangkal lidah menyentuh langit-langit keras. Seperti K dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Ka',  'arabic' => 'كَ'],
                'kasrah'  => ['latin' => 'Ki',  'arabic' => 'كِ'],
                'dhammah' => ['latin' => 'Ku',  'arabic' => 'كُ'],
            ],
            [
                'char_arabic' => 'ل',
                'name' => 'Lam',
                'read_latin' => 'La',
                'order_sequence' => 23,
                'pronunciation_desc' => 'Ujung sisi lidah menyentuh gusi atas bagian depan.',
                'fathah'  => ['latin' => 'La',  'arabic' => 'لَ'],
                'kasrah'  => ['latin' => 'Li',  'arabic' => 'لِ'],
                'dhammah' => ['latin' => 'Lu',  'arabic' => 'لُ'],
            ],
            [
                'char_arabic' => 'م',
                'name' => 'Mim',
                'read_latin' => 'Ma',
                'order_sequence' => 24,
                'pronunciation_desc' => 'Kedua bibir terkatup rapat, udara keluar melalui hidung.',
                'fathah'  => ['latin' => 'Ma',  'arabic' => 'مَ'],
                'kasrah'  => ['latin' => 'Mi',  'arabic' => 'مِ'],
                'dhammah' => ['latin' => 'Mu',  'arabic' => 'مُ'],
            ],
            [
                'char_arabic' => 'ن',
                'name' => 'Nun',
                'read_latin' => 'Na',
                'order_sequence' => 25,
                'pronunciation_desc' => 'Ujung lidah menyentuh gusi atas, udara keluar melalui hidung.',
                'fathah'  => ['latin' => 'Na',  'arabic' => 'نَ'],
                'kasrah'  => ['latin' => 'Ni',  'arabic' => 'نِ'],
                'dhammah' => ['latin' => 'Nu',  'arabic' => 'نُ'],
            ],
            [
                'char_arabic' => 'و',
                'name' => 'Wau',
                'read_latin' => 'Wa',
                'order_sequence' => 26,
                'pronunciation_desc' => 'Kedua bibir membulat ke depan. Seperti W dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Wa',  'arabic' => 'وَ'],
                'kasrah'  => ['latin' => 'Wi',  'arabic' => 'وِ'],
                'dhammah' => ['latin' => 'Wu',  'arabic' => 'وُ'],
            ],
            [
                'char_arabic' => 'ه',
                'name' => "Ha'",
                'read_latin' => 'Ha',
                'order_sequence' => 27,
                'pronunciation_desc' => 'Keluar dari pangkal tenggorokan paling dalam. Terdengar seperti hembusan nafas.',
                'fathah'  => ['latin' => 'Ha',  'arabic' => 'هَ'],
                'kasrah'  => ['latin' => 'Hi',  'arabic' => 'هِ'],
                'dhammah' => ['latin' => 'Hu',  'arabic' => 'هُ'],
            ],
            [
                'char_arabic' => 'لا',
                'name' => 'Lam Alif',
                'read_latin' => 'Laa',
                'order_sequence' => 28,
                'pronunciation_desc' => 'Gabungan Lam dan Alif. Huruf khusus dalam alfabet Hijaiyah.',
                'fathah'  => ['latin' => 'Laa', 'arabic' => 'لاَ'],
                'kasrah'  => ['latin' => 'Lii', 'arabic' => 'لاِ'],
                'dhammah' => ['latin' => 'Luu', 'arabic' => 'لاُ'],
            ],
            [
                'char_arabic' => 'ء',
                'name' => 'Hamzah',
                'read_latin' => 'A',
                'order_sequence' => 29,
                'pronunciation_desc' => 'Suara hentian glottal dari pangkal tenggorokan.',
                'fathah'  => ['latin' => 'A',   'arabic' => 'ءَ'],
                'kasrah'  => ['latin' => 'I',   'arabic' => 'ءِ'],
                'dhammah' => ['latin' => 'U',   'arabic' => 'ءُ'],
            ],
            [
                'char_arabic' => 'ي',
                'name' => 'Ya',
                'read_latin' => 'Ya',
                'order_sequence' => 30,
                'pronunciation_desc' => 'Tengah lidah naik ke langit-langit mulut. Seperti Y dalam bahasa Indonesia.',
                'fathah'  => ['latin' => 'Ya',  'arabic' => 'يَ'],
                'kasrah'  => ['latin' => 'Yi',  'arabic' => 'يِ'],
                'dhammah' => ['latin' => 'Yu',  'arabic' => 'يُ'],
            ],
        ];

        foreach ($letters as $letter) {
            Letter::create($letter);
        }
    }
}
